//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("23 .Net Api Library")]
[assembly: AssemblyDescription(".Net library for accessing 23hq.com Api functionality")]
[assembly: AssemblyCompany("http://23net.github.com")]
[assembly: AssemblyProduct("23 .Net Api Library")]
[assembly: AssemblyCopyright("Copyright © Daniel Isenmann 2016")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("3.14.0.0")]


